# Generated by Django 4.2.7 on 2023-12-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0002_customuser_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verified',
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_login_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
