# Generated by Django 4.2.7 on 2023-12-11 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0003_remove_customuser_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_login_date',
        ),
    ]
