# Generated by Django 5.0.2 on 2024-02-15 03:47

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0005_alter_customuser_options_alter_customuser_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='País'),
        ),
    ]
