# Generated by Django 5.0.2 on 2024-02-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0006_alter_customuser_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.TextField(default='Santiago', verbose_name='Ciudad'),
        ),
    ]
