# Generated by Django 5.0.2 on 2024-02-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0007_customuser_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.TextField(default='', verbose_name='Ciudad'),
        ),
    ]
