# Generated by Django 5.0.2 on 2024-02-12 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_task_priority_alter_task_task_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.tag'),
        ),
    ]
