# Generated by Django 5.0.2 on 2024-02-21 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_task_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_tag',
            field=models.ForeignKey(default='Tarea', on_delete=django.db.models.deletion.SET_DEFAULT, to='task.tag'),
        ),
    ]
