# Generated by Django 5.0.2 on 2024-02-23 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_alter_task_task_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='background_color',
            field=models.CharField(default='#fdf7e5', max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_priority',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='task.priority'),
        ),
    ]
